name: spm

on:
  pull_request:
  schedule:
    # Run every day at 11pm (PST) - cron uses UTC times
    - cron:  '0 7 * * *'

jobs:
  swiftpm-build-tests:
    permissions:
      contents: read
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: Initialize xcodebuild
      run: xcodebuild -list
    - name: Install Simulators
      uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
      with:
        timeout_minutes: 15
        max_attempts: 5
        retry_wait_seconds: 120
        continue_on_error: true
        command: |
          xcodebuild -downloadPlatform iOS
          xcodebuild -downloadPlatform tvOS
    - name: iOS Simulator Build Tests
      run: xcodebuild -scheme BoringSSL-GRPC build -sdk 'iphonesimulator' -destination 'generic/platform=iOS Simulator'
    - name: macos Build Tests
      run: xcodebuild -scheme BoringSSL-GRPC build -sdk 'macosx' -destination 'platform=OS X,arch=x86_64',
    - name: tvOS Build Tests
      run: xcodebuild -scheme BoringSSL-GRPC build -sdk "appletvsimulator" -destination 'generic/platform=tvOS Simulator'
    - name: iOS Device Build Tests
      run: xcodebuild -scheme BoringSSL-GRPC build -sdk 'iphoneos' -destination 'generic/platform=iOS'
